# app相关基础信息
app:
  name: "test_case_1"  # 项目名称
  runType: "dev"  # 运行模式

# http 服务
httpServer:
  open: true
  prod: 12345 # 端口

# grpc 服务
grpcServer:
  open: true
  prod: 12346
  log: true # 打印日志

# grpc 客户端
grpcClient:
  prod: true

# tcp 服务
tcpServer:
  open: true
  prod: 12347

# tcp 客户端
tcpClient:
  prod: 12348

# udp 服务
udpServer:
  open: true
  prod: 12349

# udp 客户端
udpClient:
  prod: 12348

# redis 配置
redis:
  -
    name: "redis1"
    host: "127.0.0.1"
    port: "3306"
    db: 1
    password: ""
    maxIdle: 10  # 最大 Idle 连接
    maxActive: 50 # 最大 活跃 连接

# mysql 配置
mysql:
  -
    dbname: "test"
    user: "root"
    password: "123"
    host: "127.0.0.1"
    port: "3306"


mqType: ""


nsq:
  producer: ""
  consumer: ""

rabbit:
  addr: ""
  user: ""
  password: ""

kafka:
  addr: ""

mongo:
  host: ""
  user: ""
  password: ""

ttf: ""


cluster:
  open: ""
  myAddr: ""
  initCluster: ""


logCentre:
  host: ""
  prod: ""


jwt:
  secret: ""
  expire: ""


minio:
  host: ""
  access: ""
  secret: ""
